---
- name: Create GREEN VLAN
  eos_vlan: name=GREEN vlanid=100
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

- name: Create ORANGE VLAN
  eos_vlan: name=ORANGE vlanid=200
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

- name: Create CYAN VLAN
  eos_vlan: name=CYAN vlanid=300
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https  
