---
- name: Create GREEN VLAN
  eos_vlan: name=GREEN vlanid=100
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

- name: Create ORANGE VLAN
  eos_vlan: name=ORANGE vlanid=200
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

- name: Create CYAN VLAN
  eos_vlan: name=CYAN vlanid=300
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

- name: Set Ethernet4 description
  eos_interface: name=Ethernet4 description="*** IN USE ***"
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https

#- name: Configure Ethernet4 to access port on VLAN 300
#  eos_switchport: name=Ethernet4 mode=access access_vlan=300
#    username={{ eapi_username }}
#    password={{ eapi_password }}
#    host={{ eapi_hostname }}
#    port={{ eapi_port }}
#    transport=https

- name: Configure Ethernet4 to trunk port for VLANs 100, 200, 300
  eos_switchport: name=Ethernet4 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=100,200,300
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https
